about_me/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.about, name='about'),
    path('curriculum/', views.StudiesView.as_view(), name='curriculum'),
    path('projects/', views.projects, name='projects'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('calculators/', include('calculators.urls', namespace='calculators')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculators/urls.py
from django.urls import path

from . import views

app_name = 'calculators'

urlpatterns = [
    path('sample/', views.sample, name='sample'),
    path('z_criteria/', views.z_criteria, name='z_criteria'),
    path('nps/', views.nps, name='nps'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about_me.urls')),
]

calculators/models.py
from django.db import models

# Create your models here.

calculators/forms.py
from django import forms


class ZCriteriaForm(forms.Form):
    perc_1 = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field'}), label="1-st %")
    sample_1 = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field'}), label="1-st sample")
    perc_2 = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field'}), label="2-d %")
    sample_2 = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field'}), label="2-d sample")

    def clean(self):
        cleaned_data = super().clean()
        perc_1 = cleaned_data['perc_1']
        perc_2 = cleaned_data['perc_2']
        sample_1 = cleaned_data['sample_1']
        sample_2 = cleaned_data['sample_2']

        if (perc_1 < 0 or perc_1 > 100) or (perc_2 < 0 or perc_2 > 100):
            self.add_error('perc_1', 'Input error. \"%\" must be from 0 to 100')
        if perc_1 == perc_2:
            self.add_error('perc_1', 'Input error. \"%\" must not be equal')
        if sample_1 < 0 or sample_2 < 0:
            self.add_error('perc_1', 'Input error. \"Sample\" must be >0')


class SampleForm(forms.Form):
    prob = forms.CharField(widget=forms.RadioSelect(
        choices=[
            ('80%', '80%'),
            ('90%', '90%'),
            ('95%', '95%'),
            ('99%', '99%'),
        ]),
        required='required',
        label='Probability')
    sample = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field'}), label="Sample")
    u = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field', 'value': '50'}),
                         label="%")
    gen_sample = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input_field', 'value': '140000000'}),
                                  label="General population")

    def clean(self):
        cleaned_data = super().clean()

        sample = cleaned_data['sample']
        u = cleaned_data['u']
        gen_sample = cleaned_data['gen_sample']

        if gen_sample < sample:
            self.add_error('sample', 'The sample is lesser than GP')
        if sample <= 0:
            self.add_error('sample', 'Input error. Must be > 0')
        if gen_sample <= 0:
            self.add_error('gen_sample', 'Input error. Must be > 0')
        if u < 0 or u > 100:
            self.add_error('u', 'Input error. Must be from 0 to 100')


class NpsForm(forms.Form):
    crit1 = forms.FloatField(widget=(forms.NumberInput(attrs={'class': 'input_field', 'placeholder': 'Critics 0-6'})))
    neut1 = forms.FloatField(
        widget=(forms.NumberInput(attrs={'class': 'input_field', 'placeholder': 'Neutralists 7-8'})))
    prom1 = forms.FloatField(
        widget=(forms.NumberInput(attrs={'class': 'input_field', 'placeholder': 'Promoters 9-10'})))
    crit2 = forms.FloatField(widget=(forms.NumberInput(attrs={'class': 'input_field', 'placeholder': 'Critics 0-6'})))
    neut2 = forms.FloatField(
        widget=(forms.NumberInput(attrs={'class': 'input_field', 'placeholder': 'Neutralists 7-8'})))
    prom2 = forms.FloatField(
        widget=(forms.NumberInput(attrs={'class': 'input_field', 'placeholder': 'Promoters 9-10'})))

    def clean(self):
        cleaned_data = super().clean()

        var_list1 = [
            cleaned_data['crit1'],
            cleaned_data['neut1'],
            cleaned_data['prom1']
        ]

        var_list2 = [
            cleaned_data['crit2'],
            cleaned_data['neut2'],
            cleaned_data['prom2']
        ]

        if any(i < 0 for i in var_list1):
            self.add_error("crit1", "Input error. Some values < 0")

        if any(i < 0 for i in var_list2):
            self.add_error("crit2", "Input error. Some values < 0")

calculators/views.py
from django.shortcuts import render
from .forms import ZCriteriaForm, SampleForm, NpsForm
from math import sqrt


def calc_error(form):
    values = {
        '80%': '1.2815515655',
        '90%': '1.6448536270',
        '95%': '1.9599639845',
        '99%': '2.5758293035',
    }

    z = form.cleaned_data['prob']
    zp = float(values[z])

    u = form.cleaned_data['u']
    sam = form.cleaned_data['sample']
    gen = form.cleaned_data['gen_sample']

    answer = zp * sqrt((u ** 2 / sam) * (1 - sam / gen))

    return round(answer, 2)


def sample(request):
    if request.method == 'POST':
        form = SampleForm(request.POST)
        if form.is_valid():
            context = {
                'title': 'sample-c',
                'answer': calc_error(form),
                'form': form,
            }
            return render(request, 'calculators/sample.html', context)
    else:
        form = SampleForm()

    context = {
        'title': 'sample',
        'form': form,
    }

    return render(request, 'calculators/sample.html', context)


def z_calc(form):
    values = {
        '80%': '1.2815515655',
        '90%': '1.6448536270',
        '95%': '1.9599639845',
        '99%': '2.5758293035',
    }

    perc_1 = form.cleaned_data['perc_1'] / 100
    perc_2 = form.cleaned_data['perc_2'] / 100
    sample_1 = form.cleaned_data['sample_1']
    sample_2 = form.cleaned_data['sample_2']

    first = ((perc_1) * (1 - perc_1)) / sample_1
    second = ((perc_2) * (1 - perc_2)) / sample_2

    z = abs(perc_1 - perc_2) / (sqrt(first + second))

    answer = {}

    for k, v in values.items():
        if z > float(v):
            answer[k] = 'Sig. diff'
        else:
            answer[k] = 'No sig. diff'

    return answer


def z_criteria(request):
    if request.method == 'POST':
        form = ZCriteriaForm(request.POST)
        if form.is_valid():
            context = {
                'title': 'z_criteria',
                'answer': z_calc(form),
                'form': form,
            }
            return render(request, 'calculators/z_criteria.html', context)
    else:
        form = ZCriteriaForm()

    context = {
        'title': 'z_criteria',
        'form': form,
    }

    return render(request, 'calculators/z_criteria.html', context)


def nps_calc(form):
    values = {
        '80%': '1.2815515655',
        '90%': '1.6448536270',
        '95%': '1.9599639845',
        '99%': '2.5758293035',
    }

    crit1 = form.cleaned_data['crit1']
    neut1 = form.cleaned_data['neut1']
    prom1 = form.cleaned_data['prom1']
    crit2 = form.cleaned_data['crit2']
    neut2 = form.cleaned_data['neut2']
    prom2 = form.cleaned_data['prom2']

    base1 = crit1 + neut1 + prom1
    nps1 = round(100 * ((prom1 / base1) - (crit1 / base1)), 2)

    base2 = crit2 + neut2 + prom2
    nps2 = round(100 * ((prom2 / base2) - (crit2 / base2)), 2)

    average1 = ((1 * prom1) + (-1 * crit1)) / base1
    average2 = ((1 * prom2) + (-1 * crit2)) / base2

    p1 = (1 - average1) ** 2
    n1 = (0 - average1) ** 2
    k1 = (-1 - average1) ** 2

    p2 = (1 - average2) ** 2
    n2 = (0 - average2) ** 2
    k2 = (-1 - average2) ** 2

    s1 = (((p1 * prom1) + (n1 * neut1) + (k1 * crit1)) / (base1 - 1)) ** 0.5
    s2 = (((p2 * prom2) + (n2 * neut2) + (k2 * crit2)) / (base2 - 1)) ** 0.5

    se1 = s1 / (base1 ** 0.5)
    se2 = s2 / (base2 ** 0.5)

    z = abs((average1 - average2) / sqrt((se1 ** 2) + (se2 ** 2)))

    answer = {'npsmeans': {'nps1': f'NPS1 -> {nps1}', 'nps2': f'NPS2 -> {nps2}'},
              'sig': {},
              }

    for k, v in values.items():
        if z > float(v):
            answer['sig'][k] = 'Sig. diff'
        else:
            answer['sig'][k] = 'No sig. diff'

    return answer


def nps(request):
    if request.method == 'POST':
        form = NpsForm(request.POST)
        if form.is_valid():
            calculate = nps_calc(form)
            context = {
                'title': 'nps',
                'answer': calculate['sig'],
                'nps1': calculate['npsmeans']['nps1'],
                'nps2': calculate['npsmeans']['nps2'],
                'form': form,
            }
            return render(request, 'calculators/nps.html', context)
    else:
        form = NpsForm()

    context = {
        'title': 'nps',
        'form': form,
    }
    return render(request, 'calculators/nps.html', context)

calculators/templates/calculators/nps.html
{% extends 'extensions/layout.html' %}
{% load static %}

{% block title %}
{{ title|upper }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">NPS</p>
        <p class="text_allpages">Calculate statistical difference between NPS</p>
    </div>
</div>
{% endblock %}

{% block maincontent %}

<div class="main_nps container_width">
    {% if form %}

    <form method="post" class="main_nps_form">
        {% csrf_token %}

        <div class="samples">
            <div class="first_sample">
                <h3>Sample 1</h3>
                <p>
                    {% if nps1 %}
                    {{ nps1 }}
                    {% endif %}
                </p>
                {{ form.crit1 }}
                {{ form.neut1 }}
                {{ form.prom1 }}
                {{ form.errors.crit1 }}
            </div>

            <div class="second_sample">
                <h3>Sample 2</h3>
                <p>
                    {% if nps2 %}
                    {{ nps2 }}
                    {% endif %}
                </p>
                {{ form.crit2 }}
                {{ form.neut2 }}
                {{ form.prom2 }}
                {{ form.errors.crit2 }}
            </div>
        </div>

        <div class="buttons">
            <input type="submit" value="Calculate" class="btn btn-primary">
            <a class="btn btn-warning" href="{% url 'calculators:nps' %}">Reset page</a>
        </div>

    </form>

    <div class="main_nps_answer">
        {% if answer %}

        {% for k, v in answer.items %}
        {% if v == 'Sig. diff' %}
        <div class="test_yes">
            {{ k }}
            {{ v }}
        </div>
        {% else %}
        <div class="test_no">
            {{ k }}
            {{ v }}
        </div>
        {% endif %}
        {% endfor %}

        {% endif %}
    </div>

    {% endif %}
</div>

{% endblock %}

calculators/templates/calculators/sample.html
{% extends 'extensions/layout.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">Sample</p>
        <p class="text_allpages">Calculate sample error</p>
    </div>
</div>
{% endblock %}

{% block maincontent %}

<div class="main_sample container_width">
    {% if form %}
        <form method="post" class="main_sample_form">
            {% csrf_token %}

            {{ form.as_p }}

            <div class="buttons">
                <input type="submit" value="Calculate" class="btn btn-primary">
                <a class="btn btn-warning" href="{% url 'calculators:sample' %}">
                    Reset page
                </a>
            </div>
        </form>

        {% if answer %}
            <p class="main_sample_answer">
                &nbsp;{{ answer }}
            </p>
        {% endif %}
    {% endif %}

</div>

{% endblock %}

calculators/templates/calculators/z_criteria.html
{% extends 'extensions/layout.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">
            <nobr>Z-criteria</nobr>
        </p>
        <p class="text_allpages">Calculate the statistical difference between shares
            <nobr>Z-criteria</nobr>
        </p>
    </div>
</div>
{% endblock %}

{% block maincontent %}

<div class="main_zcriteria container_width">

    <form class="main_zcriteria_form" method="post">
        {% csrf_token %}

        {% if form %}

        {{ form.as_p }}

        {% endif %}

        <div class="buttons">
            <input type="submit" value="Calculate" class="btn btn-primary">
            <a class="btn btn-warning" href="{% url 'calculators:z_criteria' %}">Reset page</a>
        </div>
    </form>

    <div class="main_zcriteria_answer">
        {% if answer %}

        {% for k, v in answer.items %}

        {% if v == 'Sig. diff' %}
        <div class="test_yes">
            {{ k }}
            {{ v }}
            <span>
                ({{ form.cleaned_data.perc_1 }}% vs. {{ form.cleaned_data.perc_2 }}%)
            </span>
        </div>
        {% else %}
        <div class="test_no">
            {{ k }}
            {{ v }}
            <span>
                ({{ form.cleaned_data.perc_1 }}% vs. {{ form.cleaned_data.perc_2 }}%)
            </span>
        </div>
        {% endif %}

        {% endfor %}

        {% endif %}
    </div>

</div>

{% endblock %}