about_me/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.about, name='about'),
    path('curriculum/', views.StudiesView.as_view(), name='curriculum'),
    path('projects/', views.projects, name='projects'),
    path('news/', views.NewsView.as_view(), name='news'),
    path('contacts/', views.ContactsView.as_view(), name='contacts'),
    path('calculators/', include('calculators.urls', namespace='calculators')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('about_me.urls')),
]

about_me/models.py
from django.db import models
from datetime import datetime


class Courses(models.Model):
    number = models.SmallIntegerField(primary_key=True)
    title = models.CharField(max_length=70)
    result = models.CharField(max_length=150, blank=True)
    status = models.BooleanField(default=0, name="Completed")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['number']

        verbose_name = 'Course'
        verbose_name_plural = 'Courses'


class Classes(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    lessons = models.CharField(max_length=100)

    def __str__(self):
        return self.lessons

    class Meta:
        verbose_name = 'Class'
        verbose_name_plural = 'Classes'


class News(models.Model):
    title = models.CharField(max_length=100, default=None)
    description = models.TextField(default=None)
    datetime = models.DateTimeField(default=datetime.now())
    picture = models.ImageField(default=None)
    status = models.BooleanField(default=1, name="Completed")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'


class Messages(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    text = models.TextField(verbose_name='message')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

about_me/forms.py
from django.forms import ModelForm, forms
from .models import Messages


class MessForm(ModelForm):
    class Meta:
        model = Messages
        fields = ['name', 'email', 'text']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form_field'
            if field_name == 'name':
                field.widget.attrs['placeholder'] = 'Your name'
            elif field_name == 'email':
                field.widget.attrs['placeholder'] = 'Your e-mail'
            elif field_name == 'text':
                field.widget.attrs['placeholder'] = 'Print a message'

    def clean_name(self):
        name = self.cleaned_data['name']
        if not name.isalpha():
            raise forms.ValidationError(f"Type only the letters \"{name}\"")

        return name

about_me/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView

from .models import Courses, News
from .forms import MessForm


class ContextDataMixin:
    title = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


def about(request):
    context = {'title': 'about me'}
    return render(request, 'about_me/index.html', context)


class StudiesView(ContextDataMixin, ListView):
    model = Courses
    template_name = 'about_me/curriculum.html'
    title = 'Curriculum'


def projects(request):
    context = {'title': 'projects'}
    return render(request, 'about_me/projects.html', context)


class NewsView(ContextDataMixin, ListView):
    model = News
    template_name = 'about_me/news.html'
    title = 'News'


class ContactsView(ContextDataMixin, CreateView):
    form_class = MessForm
    template_name = 'about_me/contacts.html'
    title = 'News'

# def contacts(request):
#     if request.method == 'POST':
#         date_from_form = MessForm(request.POST)
#         if date_from_form.is_valid():
#             date_from_form.save()
#             return redirect('contacts')
#     else:
#         date_from_form = MessForm()
#
#     context = {
#         'title': 'contacts',
#         'date_from_form': date_from_form
#     }
#
#     return render(request, 'about_me/contacts.html', context)

about_me/templates/about_me/contacts.html
{% extends 'extensions/layout.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">Contacts</p>
        <p class="text_allpages">The page describes possible ways to&nbsp;contact me.<br> Will be&nbsp;glad to&nbsp;hear
            from you!</p>
    </div>
</div>
{% endblock %}
<div class="main_contacts">

</div>

{% block maincontent %}

<div class="main_contacts container_width">
    <div class="main_contacts_section">
        <div class="main_contacts_section_text">
            <img src="{% static 'img/contacts.jpg' %}" alt="contacts">
            <p class="contact_headline">LOCATION</p>
            <p class="contact_text">RU, 101000 - Moscow </p>
            <p class="contact_headline">E-MAIL</p>
            <p class="contact_text">Burian-iliyar@yandex.ru</p>
            <p class="contact_headline">PHONE</p>
            <p class="contact_text">+7 (909) 967 56 53</p>
            <p class="contact_headline">ONLINE</p>
            <ul class="contact_list">
                <li>
                    <a href="https://www.linkedin.com/in/ilya-buryan-13889b192/" target="_blank">
                        <img class="footer_networks" src="{% static 'img/linkedin.svg' %}" alt="Linkedin">
                    </a>
                </li>
                <li>
                    <a href="https://www.facebook.com/profile.php?id=100029358050577" target="_blank">
                        <img class="footer_networks" src="{% static 'img/facebook.svg' %}" alt="Facebook">
                    </a>
                </li>
            </ul>
        </div>

        <div class="main_contacts_section_form">
            <form method="post">
                {% csrf_token %}

                {% if form %}
                {{ form.as_p }}
                {% endif %}

                <input type="submit" value="Send" class="btn btn-primary">
                <a class="btn btn-warning wid" href="{% url 'contacts' %}">Reset page</a>
            </form>
        </div>
    </div>

    <iframe
        src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d53289.88443700247!2d37.595586242294395!3d55.7685022567757!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sen!4v1614178626200!5m2!1sen!2sen"
        width="100%" height="250" style="border:0; margin-bottom: 20px;" loading="lazy">
    </iframe>
</div>

{% endblock %}

about_me/templates/about_me/curriculum.html
{% extends 'extensions/layout.html' %}


{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">My studies</p>
        <p class="text_allpages">The page describes my studies in&nbsp;Geek Brains University,
            at the faculty&nbsp;of Python development</p>
    </div>
</div>
{% endblock %}

{% block maincontent %}
<br>
<button type="button" class="btn btn-info hide-btn">Show / Hide description</button>
<br>
<div class="main_flex">
    {% if object_list %}

    {% for ex in object_list %}
    <div class="main_done">

        {% if ex.Completed == True %}
        <div class="main_done_element">
            <div class="main_done_sign">
                <p>Completed</p>
            </div>
        </div>
        {% else %}
        <div class="main_done_not_element">
            <div class="main_done_not_sign">
                <p>Coming soon</p>
            </div>
        </div>
        {% endif %}

        <div class="main_section_study container_width">
            <span class="main_section_study_headline">{{ ex.title }}</span>
            <span class="main_section_study_text_list_item_i">{{ ex.result }}</span>
            <hr class="main_section_study_hr">
            <p class="main_section_study_text_list_item">Curriculum:</p>
            <div class="main_section_study_text">
                <ol class="main_section_study_text_list">
                    {% for i in ex.classes_set.all %}
                    <li class="main_section_study_text_list_item">{{ i.lessons }}</li>
                    {% endfor %}
                </ol>
            </div>
        </div>

    </div>
    {% endfor %}

    {% endif %}
</div>

{% endblock %}

about_me/templates/about_me/news.html
{% extends 'extensions/layout.html' %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">News</p>
        <p class="text_allpages">The page describes news and updates of&nbsp;the projects and the site</p>
    </div>
</div>
{% endblock %}

{% block maincontent %}

{% if object_list %}

<div class="main_news container_width">
    {% for i in object_list %}
    {% if i.Completed == True %}
    <div class="main_news_article">
        <div class="main_news_article_pic">
            <img class="main_news_article_img" src="/media/{{ i.picture }}" alt="news">
        </div>
        <div class="main_news_article_text">
            <p class="article_title">{{ i.title }}</p>
            <p class="article_description">{{ i.description }}</p>
            <p class="article_datetime">{{ i.datetime|date:"d-m-Y" }}</p>
        </div>
    </div>
    {% endif %}
    {% endfor %}

    {% else %}
    <p>No news</p>
    {% endif %}

    {% endblock %}
</div>

about_me/templates/about_me/projects.html
{% extends 'extensions/layout.html' %}
{% load static %}

{% block title %}
{{ title|capfirst }}
{% endblock %}

{% block header %}
<div class="header header_allpages">
    <div class="header_content container_width">
        {% include 'extensions/header_menu.html' %}
        <p class="headliner_allpages">My projects</p>
        <p class="text_allpages">The page describes projects which i&nbsp;have made during studying and the
            private time</p>
    </div>
</div>
{% endblock %}

{% block maincontent %}

<div class="main_projects container_width">

    <div class="main_project">
        <div class="main_project_head">
            <div class="main_project_head_line">
                <p>Portfolio site</p>
            </div>
            <div class="main_project_head_link">
                <p>link to &raquo;&raquo;</p>
            </div>
        </div>
        <a href="https://github.com/IlyaBuryan/portfolio" target="_blank">...visit github</a>
        <hr class="main_project_hr">
        <div class="main_project_cont">
            <div class="main_project_cont_descr">
                <a href="https://github.com/IlyaBuryan/portfolio" target="_blank">
                    <img src="{% static 'img/this.JPG' %}" alt="portfolio">
                </a>
                <p>
                    This site is&nbsp;entirely developed in&nbsp;<strong>Django</strong> for introducing myself and
                    demonstrating basic skills of&nbsp;working with Django, as it was my initial&nbsp;project. The site
                    is&nbsp;fully adaptive for 3 types of&nbsp;devices: PC, tablet, mobile phone
                    (including&nbsp; and was fully made by myself (frontend + backend) including
                    burger&nbsp;menu.<br/><br/>

                    The pages <u>&laquo;about me&raquo;</u> and <u>&laquo;projects&raquo;</u> give an&nbsp;idea about
                    me,
                    my&nbsp;motivation and projects, the experience that I&nbsp;have. Demonstrates the skills
                    of&nbsp;working with static&nbsp;information and jumping through urls.<br/><br/>

                    Pages <u>&laquo;curriculum&raquo;</u> and <u>&laquo;news&raquo;</u>. Demonstrates the ability
                    to work with ORM: &nbsp;dynamically
                    retrieve and put data into the database and to use it in the context. As&nbsp;well
                    as&nbsp;the use of&nbsp;downloadable&nbsp;media&nbsp;files via admin panel. Also the ability to
                    change the DOM
                    model<br/><br/>

                    The <u>&laquo;contacts&raquo;</u> and the <u>&laquo;calculators&raquo;</u> pages demonstrates the
                    skills
                    of&nbsp;working with forms, their interaction with the database and&nbsp;operation with the
                    calculation algorithms on&nbsp;the&nbsp;server&nbsp;side. Also connection of the e-mail service.
                </p>
            </div>
        </div>
        <hr class="main_project_hr">
        <div class="main_project_cont_tech">
            <div class="main_project_head_line">
                <p>Used stack of technologies:</p>
            </div>
            <ul class="main_section_text_list">
                <li class="main_section_text_list_item">
                    <strong>Django Framework v3.1.6</strong>
                </li>
                <li class="main_section_text_list_item">
                    Pure <strong>Python</strong>
                </li>
                <li class="main_section_text_list_item"><strong>HTML5, CSS3</strong> (SCSS, media queries,
                    Bootstrap)
                </li>
                <li class="main_section_text_list_item">
                    <strong>JavaScript</strong>
                </li>
                <li class="main_section_text_list_item">
                    <strong>Postgresql</strong> deploy
                </li>
                <li class="main_section_text_list_item">
                    Support: Gimp, Figma, Validator, Typograf, Browsershots
                </li>
            </ul>
        </div>
    </div>

    <div class="main_project">
        <div class="main_project_head">
            <div class="main_project_head_line">
                <p>Online shop</p>
            </div>
            <div class="main_project_head_link">
                <p>link to &raquo;&raquo;</p>
            </div>
        </div>
        <a href="http://89.108.71.100:8001/" target="_blank">...visit site</a>
        <a href="https://github.com/IlyaBuryan/onlineshop" target="_blank">...visit github</a>
        <hr class="main_project_hr">
        <div class="main_project_cont">
            <div class="main_project_cont_descr">
                <a href="https://github.com/IlyaBuryan/onlineshop" target="_blank">
                    <img src="{% static 'img/onlineshop.JPG' %}" alt="onlineshop">
                </a>
                <p>
                    This site is&nbsp;made at&nbsp;an&nbsp;<strong>advanced level</strong> in&nbsp;the process
                    of&nbsp;my&nbsp;learning
                    the framework. It&nbsp;demonstrates ability to&nbsp;create a&nbsp;fully functional online store
                    website.
                    <br> <br>
                    In&nbsp;addition to&nbsp;all the standard Django toolkit mastered via the first site: working with
                    forms, templates, views, models, urls, statics and media files, this project had the following
                    features:<br/>
                <ul>
                    <li>Complicated structure, consisting of&nbsp;<strong>4 applications</strong>: own admin panel, app
                        for basket and
                        users.
                    </li>
                    <li> Implemented <strong>complex queries</strong> to&nbsp;the database. Trained much in&nbsp;Shell.
                    </li>
                    <li><strong>Inheritance</strong> and <strong>redefinition</strong> of&nbsp;the class methods are
                        applied when working
                        with forms and
                        models
                    </li>
                    <li>Adminapp is totally performed via <strong>CBV</strong></li>
                    <li>Used both <strong>get and post</strong> data transfer to&nbsp;the controllers</li>
                    <li><strong>Pagination</strong> is&nbsp;implemented on&nbsp;product pages</li>
                    <li>Implemented user <strong>authentication and registration</strong> + page access
                        <strong>decorators</strong></li>
                    <li>Trained creating <strong>template filters</strong> and <strong>management scripts</strong></li>
                </ul>
                </p>
            </div>
        </div>
        <hr class="main_project_hr">
        <div class="main_project_cont_tech">
            <div class="main_project_head_line">
                <p>Used stack of technologies:</p>
            </div>
            <ul class="main_section_text_list">
                <li class="main_section_text_list_item">
                    <strong>Django Framework v3.1.6</strong>
                </li>
                <li class="main_section_text_list_item">
                    Pure <strong>Python</strong>
                </li>
                <li class="main_section_text_list_item"><strong>HTML5, CSS3</strong> (SCSS, Bootstrap)
                </li>
                <li class="main_section_text_list_item">
                    <strong>JavaScript</strong> (+JQuery, Ajax)
                </li>
                <li class="main_section_text_list_item">
                    <strong>Postgresql</strong> deploy
                </li>
                <li class="main_section_text_list_item">
                    Support: Gimp, Figma, Validator, Typograf, Browsershots
                </li>
            </ul>
        </div>
    </div>

</div>

{% endblock %}